### ISSUE TITLE
Registration page

### ISSUE THREAD

**Issue by devvspaces** [devvspaces/EduHub#10]
Email and password are required for registration

**Comment by tutrinh16** [comment]
Hey there! Can you assign me.

**Comment by fadayopaul** [comment]
Is there available designs for the UI implementation?

**Comment by adv8j** [comment]
Hey! I'm interested in contributing so could you please provide the necessary details which you wish to include in the Registration page (like Logo, navbar/footer, or any other component). Also can you please assign this issue to me?

**Comment by orunto** [comment]
I have a prebuilt page with all the necessary functionality for this on standby. Assign this as well as the login page #11 to me

**Comment by devvspaces** [comment]
@orunto if you want to work on #11 send a comment there

**Comment by orunto** [comment]
> @orunto if you want to work on #11 send a comment there

Alright

**Comment by orunto** [comment]
@devvspaces is there an API ready for sign up? I'm done with the UI so lemme know if an API is ready for integration
