### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by devvspaces** [devvspaces/EduHub#11]
email and password are required for login
jwt is used as an authentication mechanism, make provisions for that

**Comment by duongyennhi** [comment]
I can help you create it

**Comment by duongyennhi** [comment]
May I assign it to me?

**Comment by whotterre** [comment]
Is there a design/Figma follow to follow?

**Comment by orunto** [comment]
I want to work on this issue

**Comment by devvspaces** [comment]
@hashkitti001 no there is no figma, work with imagination for now, it does not need to be beautiful, it just needs to work

**Comment by duongyennhi** [comment]
I will help you login page a user with JWT token

**Comment by devvspaces** [comment]
Yes you can
