### ISSUE TITLE
Forget password flow

### ISSUE THREAD

**Issue by devvspaces** [devvspaces/EduHub#12]
- Create a page for initiating password reset using email
- Create a page that retrieves the forget password token from the URL and calls the API to verify it, if valid then redirect the user to the reset password page
- Create a reset password page
- Integrate API for the forget password page
- Integrate API to verify the password token page
- Integrate API for resetting password page

**Comment by AKASH-PRASAD7** [comment]
Hey, I would like to work on this issue can you assign me this?

**Comment by devvspaces** [comment]
the project setup is not ready yet
can you take that

**Comment by devvspaces** [comment]
@AKASH-PRASAD7

**Comment by AKASH-PRASAD7** [comment]
> 



> the project setup is not ready yet can you take that

yeah, no problem

**Comment by orunto** [comment]
> > 
> 
> > the project setup is not ready yet can you take that
> 
> yeah, no problem

Have you done that?

**Comment by devvspaces** [comment]
@AKASH-PRASAD7 are you still planning to work on this?

**Comment by orunto** [comment]
@devvspaces assign this to me
